version: 2

models:
  - name: stg_bt_order_info
    description: ""
    columns:
      - name: order_id
        description: ""

      - name: customer_id
        description: ""

      - name: order_status
        description: ""

      - name: order_date
        description: ""

      - name: required_date
        description: ""

      - name: shipped_date
        description: ""

      - name: item_id
        description: ""

      - name: product_id
        description: ""

      - name: quantity
        description: ""

      - name: list_price
        description: ""

      - name: discount
        description: ""

      - name: customer_first_name
        description: ""

      - name: customer_last_name
        description: ""

      - name: customer_phone
        description: ""

      - name: customer_email
        description: ""

      - name: customer_street
        description: ""

      - name: customer_city
        description: ""

      - name: customer_state
        description: ""

      - name: customer_zip_code
        description: ""

      - name: staff_id
        description: ""

      - name: first_name
        description: ""

      - name: last_name
        description: ""

      - name: email
        description: ""

      - name: phone
        description: ""

      - name: active
        description: ""

      - name: manager_id
        description: ""

      - name: manager_first_name
        description: ""

      - name: manager_last_name
        description: ""

      - name: manager_email
        description: ""

      - name: manager_phone
        description: ""

      - name: manager_active
        description: ""

      - name: manager_manager_id
        description: ""

      - name: store_id
        description: ""

      - name: store_name
        description: ""

      - name: store_phone
        description: ""

      - name: store_email
        description: ""

      - name: street
        description: ""

      - name: city
        description: ""

      - name: state
        description: ""

      - name: zip_code
        description: ""

  - name: stg_bt_product_info
    description: ""
    columns:
      - name: product_id
        description: ""

      - name: product_name
        description: ""

      - name: brand_id
        description: ""

      - name: category_id
        description: ""

      - name: model_year
        description: ""

      - name: list_price
        description: ""

      - name: category_name
        description: ""

      - name: brand_name
        description: ""

  - name: stg_bt_staff_info
    description: ""
    columns:
      - name: staff_id
        description: ""

      - name: first_name
        description: ""

      - name: last_name
        description: ""

      - name: email
        description: ""

      - name: phone
        description: ""

      - name: active
        description: ""

      - name: manager_id
        description: ""

      - name: manager_first_name
        description: ""

      - name: manager_last_name
        description: ""

      - name: manager_email
        description: ""

      - name: manager_phone
        description: ""

      - name: manager_active
        description: ""

      - name: manager_manager_id
        description: ""

      - name: store_id
        description: ""

      - name: store_name
        description: ""

      - name: store_phone
        description: ""

      - name: store_email
        description: ""

      - name: street
        description: ""

      - name: city
        description: ""

      - name: state
        description: ""

      - name: zip_code
        description: ""

  - name: stg_bt_stocks_info
    description: ""
    columns:
      - name: quantity
        description: ""

      - name: product_id
        description: ""

      - name: product_name
        description: ""

      - name: brand_id
        description: ""

      - name: category_id
        description: ""

      - name: model_year
        description: ""

      - name: list_price
        description: ""

      - name: category_name
        description: ""

      - name: brand_name
        description: ""

      - name: store_id
        description: ""

      - name: store_name
        description: ""

      - name: phone
        description: ""

      - name: email
        description: ""

      - name: street
        description: ""

      - name: city
        description: ""

      - name: state
        description: ""

      - name: zip_code
        description: ""

